-- AlterTable
ALTER TABLE "bookings" ALTER COLUMN "startTime" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "endTime" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(3);
